<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Penghapusan extends Model
{
    protected $table ='penghapusan';
    protected $fillable = [
        'id',
        'id_tempat',
        'id_pemilik',
        'id_pengguna',
        'prs_diskon',
        'user',
        'blok',
        'tgl_tagihan',
        'tgl_expired',
        'bln_tagihan',
        'thn_tagihan',
        'tgl_bayar',
        'bln_bayar',
        'thn_bayar',
        'stt_lunas',
        'stt_bayar',
        'awal_air',
        'akhir_air',
        'pakai_air',
        'byr_air',
        'pemeliharaan_air',
        'beban_air',
        'arkot_air',
        'ttl_air',
        'rea_air',
        'sel_air',
        'den_air',
        'daya_listrik',
        'awal_listrik',
        'akhir_listrik',
        'pakai_listrik',
        'byr_listrik',
        'rekmin_listrik',
        'blok1_listrik',
        'blok2_listrik',
        'beban_listrik',
        'bpju_listrik',
        'ttl_listrik',
        'rea_listrik',
        'sel_listrik',
        'den_listrik',
        'ttl_keamananipk',
        'rea_keamananipk',
        'sel_keamananipk',
        'ttl_kebersihan',
        'rea_kebersihan',
        'sel_kebersihan',
        'ttl_airkotor',
        'rea_airkotor',
        'sel_airkotor',
        'ttl_lain',
        'rea_lain',
        'sel_lain',
        'ttl_tagihan',
        'diskon_tagihan',
        'rea_tagihan',
        'sel_tagihan',
        'den_tagihan',
        'stt_denda',
        'stt_bongkar',
        'stt_kebersihan',
        'stt_keamananipk',
        'stt_listrik',
        'stt_airbersih',
        'bln_linkaja',
        'ket',
        'updated_at',
        'created_at'
    ];
}
